### ISSUE TITLE
$ref tag side by side with objects

### ISSUE THREAD

**Issue by TheGreatRefrigerator** [WindomZ/swagger-merger#34]
Hi @WindomZ, thank you for this package,
i encountered unresolved paths, if they are on the same level as other objects.
For example my swagger yaml definitions are built like the following:
```
definitions:
  options:
    type: "object"
    properties:
     ...
  next_object:
    type:...
```

if i want to include some external definitions i do it like this:
```
definitions:
  $ref: "./defs.yaml#/definitions"
  options:
    type: "object"
    properties:
      ...
  next_object:
    type:...
```
which is not resolving the path

but if i only have the path in definitions, the path gets resolved:
```
definitions:
  $ref: "./defs.yaml#/definitions"
```
is it possible to do this somehow ?
