### ISSUE TITLE
OAS 3 support?

### ISSUE THREAD

**Issue by chrisdostert** [WindomZ/swagger-merger#39]
seems to work for open api 3. Is it "officially supported" or did I just get lucky?

**Comment by WindomZ** [comment]
This is a tool for merging swagger files and can be packaged into a local file.

Is it "unofficial support", but `$ref ` tag follows [official standards](https://swagger.io/docs/specification/using-ref/).
Should be noted that`$ref#*` is a non-standard tag, you can use it for yourself. :smile: 

The official features will become more and more powerful, this tool can be used as an extension.

**Comment by chrisdostert** [comment]
Thanks for the tool! BTW, is it possible to get an explanation of what #ref#* does? I looked at the examples but I still don't understand it.

**Comment by WindomZ** [comment]
I added some usage explanations, welcome feedback.

**Comment by danpolanco** [comment]
Does multi level support work to solve this issue? https://github.com/OAI/OpenAPI-Specification/issues/417 (I'm also having some trouble understanding it)

So it allows us to do:
```yaml
paths:
    $ref#pets: "/operations/pets.yaml"       # Multiple paths
    $ref#stores: "/operations/stores.yaml"     # Multiple paths
    $ref#users: "/operations/users.yaml"      # Multiple paths
```

instead of:
```yaml
paths:
  /pets:
    $ref: "/operations/pets.yaml"       # Multiple paths
  /stores:
    $ref: "/operations/stores.yaml"     # Multiple paths
  /users:
    $ref: "/operations/users.yaml"      # Multiple paths
```

Is that correct?
