### ISSUE TITLE
Can't merge definition that include {}

### ISSUE THREAD

**Issue by cm-iwata** [WindomZ/swagger-merger#78]
I want to merge these files

swagger.yaml

```yaml
...
paths:
  /pets/{id}:
    $ref: "./pets.yaml#/paths/~1pets~1{id}"
```

pets.yaml

```yaml
paths:
  /pets/{id}:
    get: ....
    delete: ....
```

This file structure is helpful for maintenance definition file with some IDE.

I use IntelliJ.
InteliJ can render these files Individually like this.

swagger.yaml
![image](https://user-images.githubusercontent.com/38879253/156194839-c8c90232-3a35-458c-9366-da8f8d6b2fb8.png)

pets.yaml
![image](https://user-images.githubusercontent.com/38879253/156194696-925809ad-71cc-4bfd-8750-150de60007a0.png)
I can maintenance pets.yaml with same API path in preview screen.

But, swagger-merger will skip  merge definition that include {}.
So, I can't use `/paths/~1pets~1{id}` for api definition's key

I tried fix this regular expression

https://github.com/WindomZ/swagger-merger/blob/24178ab57f3c6dae937f5e8072e9b405676e787e/lib/merge_json.js#L67

to
```js
return doc.replace(/\s*("\$ref")( *):( *)"[^"]+"\s*/gm, s => {
```

Them, I can merge these definitions.
But, I'm not sure if this fix is correct.

I'm sorry I'm not good at English
